### ISSUE TITLE
Provide Grafana dashboards

### ISSUE THREAD

**Issue by fridex** [thoth-station/pulp-metrics-exporter#17]
**Is your feature request related to a problem? Please describe.**

As an operator of Pulp deployment on Operate First, I would like to have the ability to browse metrics exposed by pulp-metrics-exporter and monitor the Pulp instance.

**Describe the solution you'd like**

Provide Grafana dashboard for metrics exposed by pulp-metrics-exporter. Notably:

- [ ] `pulp_status_connection` - connection status to Pulp
- [ ] `pulp_status_workers_count` - number of workers online
- [ ] `pulp_status_database_connection` - connection status to the database
- [ ] `pulp_status_redis_connection` = connection status to Redis
- [ ] `pulp_tasks_count` - number of tasks running in Pulp
- [ ] `pulp_python_packages_count` - number of packages available in Pulp's Python plugin
- [ ] `pulp_python_distributions_count` - number of distributions available in Pulp's Python plugin
- [ ] `pulp_python_publications_count` - number of publications available in Pulp's Python plugin
- [ ] `pulp_python_remotes_count` - number of remotes available in Pulp's Python plugin
- [ ] `pulp_python_repositories_count` - number of repositories available in Pulp's Python plugin

All these metrics are already available in pulp-metrics-exporter and exposed thought the `/metrics` endpoint.

**Comment by pacospace** [comment]
Preliminary Dashboard: https://grafana.operate-first.cloud/d/B7DLT7anz/pulp-metrics?orgId=1

**Comment by fridex** [comment]
As discussed on the last "Thoth's SIG observability" and "Python package index hosted by Red Hat" meetings, let's see if this is something Pulp team is interested to use and extend. As per discussion, metrics could be extended to show also platform metrics (such as CPU/memory consumption) or other parts of interest from the Pulp point of view.

CC @gerrod3 please keep us posted if you make any progress, not to duplicate efforts

**Comment by harshad16** [comment]
sync with the pulp team 
evaluate the work done.
